-- =============================================================================
-- V1 — esquema inicial do Paga ai
--
-- Este arquivo E o schema. Ele roda uma vez, na ordem, e depois nunca mais muda:
-- o Flyway grava um checksum e recusa subir se alguem editar um arquivo ja
-- aplicado. Para alterar o banco, crie um V2__descricao.sql novo.
--
-- SQL escrito para rodar igual em PostgreSQL (producao) e H2 (desenvolvimento).
-- Por isso NUMERIC em vez de DECIMAL, e GENERATED BY DEFAULT AS IDENTITY em vez
-- de SERIAL ou AUTO_INCREMENT.
-- =============================================================================

-- Quem entra no sistema (voce e seu socio). Nao confundir com cliente.
CREATE TABLE usuario (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login      VARCHAR(60)  NOT NULL,
    nome       VARCHAR(100) NOT NULL,
    -- BCrypt de 60 caracteres. A senha em si nunca e gravada.
    senha_hash VARCHAR(100) NOT NULL,
    papel      VARCHAR(20)  NOT NULL,
    ativo      BOOLEAN      NOT NULL,
    criado_em  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_usuario_login UNIQUE (login)
);

-- Quem deve.
CREATE TABLE cliente (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(120) NOT NULL,
    telefone    VARCHAR(30),
    instagram   VARCHAR(60),
    logradouro  VARCHAR(150),
    numero      VARCHAR(20),
    complemento VARCHAR(80),
    bairro      VARCHAR(80),
    cidade      VARCHAR(80),
    uf          VARCHAR(2),
    cep         VARCHAR(9),
    observacoes VARCHAR(500),
    ativo       BOOLEAN      NOT NULL,
    criado_em   TIMESTAMP    NOT NULL
);

-- Uma divida. valor_total nulo = cobranca recorrente, sem fim definido.
-- As PARCELAS nao existem aqui: sao calculadas por CalendarioCobranca a partir
-- de data_inicio + periodicidade + valor_parcela.
CREATE TABLE cobranca (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id    BIGINT        NOT NULL,
    descricao     VARCHAR(150)  NOT NULL,
    valor_total   NUMERIC(12,2),
    valor_parcela NUMERIC(12,2) NOT NULL,
    periodicidade VARCHAR(10)   NOT NULL,
    dia_do_mes    INTEGER,
    dia_da_semana VARCHAR(12),
    data_inicio   DATE          NOT NULL,
    data_fim      DATE,
    ativa         BOOLEAN       NOT NULL,
    criado_em     TIMESTAMP     NOT NULL,
    CONSTRAINT fk_cobranca_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

-- Dinheiro que entrou. Nao aponta para parcela nenhuma, de proposito:
-- CalculadoraDeDivida aloca da parcela mais antiga para a mais nova.
CREATE TABLE pagamento (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cobranca_id    BIGINT        NOT NULL,
    data_pagamento DATE          NOT NULL,
    valor_pago     NUMERIC(12,2) NOT NULL,
    observacao     VARCHAR(255),
    registrado_por VARCHAR(60),
    criado_em      TIMESTAMP     NOT NULL,
    CONSTRAINT fk_pagamento_cobranca FOREIGN KEY (cobranca_id) REFERENCES cobranca (id)
);

-- O painel soma os pagamentos agrupados por cobranca; sem este indice a soma
-- varre a tabela inteira quando o historico crescer.
CREATE INDEX idx_pagamento_cobranca ON pagamento (cobranca_id);

-- Buscas de cliente sao por nome, e a lista sai ordenada por ele.
CREATE INDEX idx_cliente_nome ON cliente (nome);

-- O painel so olha cobranca ativa.
CREATE INDEX idx_cobranca_cliente ON cobranca (cliente_id);
